TrainingArguments:
    epochs: 1
    warmup_steps: 500
    weight_decay: 0.01
    batch_size: 1
    learning_rate: 0.001
    logging_steps: 10
    evaluation_strategy: steps
    eval_steps: 400
    save_steps: 1e6
    gradient_accumulation_steps: 8
  
